server:
  port: 8082
  servlet:
    context-path: /dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.cj.jdbc.Driver